# Generated by Django 4.2.4 on 2023-08-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('1', 'JS'), ('2', 'Python'), ('3', 'C#'), ('4', 'C++'), ('5', 'C'), ('6', 'Ruby')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='tag',
            name='tags',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], default='1', max_length=5),
        ),
    ]
