# Generated by Django 4.2.4 on 2023-08-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_category_tag_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creationtime',
            field=models.DateField(null=True, verbose_name='Created At '),
        ),
        migrations.AlterField(
            model_name='question',
            name='creationtime',
            field=models.DateField(null=True, verbose_name='Created At '),
        ),
    ]
