# Generated by Django 4.2.4 on 2023-08-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_answer_user_fk_alter_question_user_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-creationtime']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-creationtime']},
        ),
        migrations.AddField(
            model_name='question',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='core.user'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='creationtime',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created At '),
        ),
        migrations.AlterField(
            model_name='question',
            name='creationtime',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created At '),
        ),
    ]
