# Generated by Django 4.2.4 on 2023-08-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creationtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At '),
        ),
        migrations.AlterField(
            model_name='question',
            name='creationtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At '),
        ),
    ]
