# Generated by Django 4.2.4 on 2023-08-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_answer_creationtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creationtime',
            field=models.DateTimeField(null=True, verbose_name='Created At '),
        ),
        migrations.AlterField(
            model_name='question',
            name='creationtime',
            field=models.DateTimeField(null=True, verbose_name='Created At '),
        ),
    ]
